const SERVER_INFO={name:"google-docs-api",version:"1.4.0"};
const PROTOCOL_VERSION="2024-11-05",TOKEN_URL="https://oauth2.googleapis.com/token",AUTH_URL="https://accounts.google.com/o/oauth2/v2/auth",KV_KEY="google_oauth_tokens";
const SCOPES="https://www.googleapis.com/auth/documents https://www.googleapis.com/auth/drive.file";
async function getTokens(e){const x=await e.GOOGLE_TOKENS.get(KV_KEY);return x?JSON.parse(x):null}
async function saveTokens(e,t){const o=await getTokens(e);await e.GOOGLE_TOKENS.put(KV_KEY,JSON.stringify({access_token:t.access_token,refresh_token:t.refresh_token||o?.refresh_token,expires_at:Date.now()+(t.expires_in||3600)*1000-60000}))}
async function refresh(e){const t=await getTokens(e);if(!t?.refresh_token)throw Error("No refresh token. Visit /auth to authorize.");const r=await fetch(TOKEN_URL,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:`grant_type=refresh_token&refresh_token=${encodeURIComponent(t.refresh_token)}&client_id=${encodeURIComponent(e.GOOGLE_CLIENT_ID)}&client_secret=${encodeURIComponent(e.GOOGLE_CLIENT_SECRET)}`});if(!r.ok)throw Error(`Token refresh failed (${r.status}): ${await r.text()}`);const d=await r.json();await saveTokens(e,d);return d.access_token}
async function token(e){const t=await getTokens(e);if(!t)throw Error("Not authorized. Visit /auth to connect Google.");return Date.now()<t.expires_at?t.access_token:refresh(e)}
async function api(e,b,m,p,x){const h={Authorization:`Bearer ${await token(e)}`,Accept:"application/json"};if(x!==undefined)h["Content-Type"]="application/json";const r=await fetch(b+p,{method:m,headers:h,body:x===undefined?undefined:JSON.stringify(x)}),s=await r.text();if(!r.ok)return{_error:true,status:r.status,body:s};try{return JSON.parse(s)}catch{return s}}
const docs=(e,m,p,b)=>api(e,"https://docs.googleapis.com/v1",m,p,b),drive=(e,m,p,b)=>api(e,"https://www.googleapis.com/drive/v3",m,p,b);
const out=x=>({content:[{type:"text",text:typeof x==="string"?x:JSON.stringify(x,null,2)}]}),url=id=>`https://docs.google.com/document/d/${id}/edit`;
const S={type:"string"},N={type:"number"},B={type:"boolean"},O={type:"object"};
function T(name,description,properties,required=[]){return{name,description,inputSchema:{type:"object",properties,required}}}
const TOOLS=[
 T("doc_create","Create a Google Doc with initial text.",{title:S,content:S,folderId:S},["title","content"]),
 T("doc_get","Read a Google Doc, including all tab content, as plain text.",{documentId:S},["documentId"]),
 T("doc_get_structure","Read the full structured Google Docs model, including tabs, paragraphs, tables, styles, and indexes.",{documentId:S},["documentId"]),
 T("doc_list_tabs","List all tabs and nested child tabs in a Google Doc.",{documentId:S},["documentId"]),
 T("doc_add_tab","Add a named tab, optionally as a child of another tab.",{documentId:S,title:S,parentTabId:S},["documentId","title"]),
 T("doc_update_tab","Rename or reorder an existing tab.",{documentId:S,tabId:S,title:S,index:N},["documentId","tabId"]),
 T("doc_delete_tab","Delete a tab by ID.",{documentId:S,tabId:S},["documentId","tabId"]),
 T("doc_append","Append text to the end of a selected tab.",{documentId:S,content:S,tabId:S},["documentId","content"]),
 T("doc_replace","Replace a selected tab's body with text.",{documentId:S,content:S,tabId:S},["documentId","content"]),
 T("doc_insert_text","Insert text at an exact index in a selected tab.",{documentId:S,index:N,content:S,tabId:S},["documentId","index","content"]),
 T("doc_delete_range","Delete a range in a selected tab.",{documentId:S,startIndex:N,endIndex:N,tabId:S},["documentId","startIndex","endIndex"]),
 T("doc_find_replace","Find and replace text throughout a document or selected tab.",{documentId:S,find:S,replace:S,matchCase:B,tabId:S},["documentId","find","replace"]),
 T("doc_update_text_style","Apply text formatting to a range in a selected tab.",{documentId:S,startIndex:N,endIndex:N,style:O,fields:S,tabId:S},["documentId","startIndex","endIndex","style","fields"]),
 T("doc_update_paragraph_style","Apply paragraph formatting to a range in a selected tab.",{documentId:S,startIndex:N,endIndex:N,style:O,fields:S,tabId:S},["documentId","startIndex","endIndex","style","fields"]),
 T("doc_insert_table","Insert a table in a selected tab.",{documentId:S,rows:N,columns:N,index:N,tabId:S},["documentId","rows","columns","index"]),
 T("doc_insert_image","Insert a public image in a selected tab.",{documentId:S,imageUrl:S,index:N,widthPt:N,heightPt:N,tabId:S},["documentId","imageUrl","index"]),
 T("doc_share","Share a Doc by link.",{documentId:S,role:S},["documentId"])
];
function tabDoc(d,id){const tabs=d.tabs||[];function walk(a){for(const t of a){if(!id||t.tabProperties?.tabId===id)return t;const z=walk(t.childTabs||[]);if(z)return z}}return walk(tabs)}
function body(d,id){const t=tabDoc(d,id);return t?.documentTab?.body||d.body||{content:[]}}
function end(d,id){const c=body(d,id).content||[],x=c[c.length-1];return x?.endIndex?x.endIndex-1:1}
function flatTabs(ts=[],parent=null){return ts.flatMap(t=>[{tabId:t.tabProperties?.tabId,title:t.tabProperties?.title,index:t.tabProperties?.index,parentTabId:parent},...flatTabs(t.childTabs||[],t.tabProperties?.tabId)])}
function range(a,s,e){const r={startIndex:s,endIndex:e};if(a.tabId)r.tabId=a.tabId;return r}
function loc(a,i){const r={index:i};if(a.tabId)r.tabId=a.tabId;return r}
async function perm(e,id,role="reader"){return fetch(`https://www.googleapis.com/drive/v3/files/${id}/permissions`,{method:"POST",headers:{Authorization:`Bearer ${await token(e)}`,"Content-Type":"application/json"},body:JSON.stringify({role,type:"anyone"})})}
async function handle(e,n,a={}){let d,r;
 switch(n){
 case"doc_create":d=await docs(e,"POST","/documents",{title:a.title});if(d._error)return out(d);if(a.content)await docs(e,"POST",`/documents/${d.documentId}:batchUpdate`,{requests:[{insertText:{location:{index:1},text:a.content}}]});if(a.folderId)await drive(e,"PATCH",`/files/${d.documentId}?addParents=${encodeURIComponent(a.folderId)}&fields=id`,{});await perm(e,d.documentId);return out({documentId:d.documentId,title:a.title,url:url(d.documentId),shared:true});
 case"doc_get":d=await docs(e,"GET",`/documents/${a.documentId}?includeTabsContent=true`);if(d._error)return out(d);return out({documentId:d.documentId,title:d.title,tabs:flatTabs(d.tabs||[]),content:(d.tabs||[]).map(t=>({tabId:t.tabProperties?.tabId,title:t.tabProperties?.title,text:(()=>{let s="";for(const x of t.documentTab?.body?.content||[])for(const y of x.paragraph?.elements||[])if(y.textRun?.content)s+=y.textRun.content;return s})()})),url:url(d.documentId)});
 case"doc_get_structure":d=await docs(e,"GET",`/documents/${a.documentId}?includeTabsContent=true`);return out(d);
 case"doc_list_tabs":d=await docs(e,"GET",`/documents/${a.documentId}?includeTabsContent=false`);return out(d._error?d:{documentId:a.documentId,tabs:flatTabs(d.tabs||[])});
 case"doc_add_tab":{const q={tabProperties:{title:a.title}};if(a.parentTabId)q.tabProperties.parentTabId=a.parentTabId;r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:[{addDocumentTab:q}]});return out({documentId:a.documentId,added:!r._error,response:r})}
 case"doc_update_tab":{const p={};if(a.title!==undefined)p.title=a.title;if(a.index!==undefined)p.index=a.index;r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:[{updateDocumentTabProperties:{tabProperties:{tabId:a.tabId,...p},fields:Object.keys(p).join(",")}}]});return out({documentId:a.documentId,updated:!r._error,response:r})}
 case"doc_delete_tab":r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:[{deleteTab:{tabId:a.tabId}}]});return out({documentId:a.documentId,deleted:!r._error,response:r});
 case"doc_append":d=await docs(e,"GET",`/documents/${a.documentId}?includeTabsContent=true`);if(d._error)return out(d);r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:[{insertText:{location:loc(a,end(d,a.tabId)),text:a.content}}]});return out({documentId:a.documentId,appended:!r._error,response:r,url:url(a.documentId)});
 case"doc_replace":d=await docs(e,"GET",`/documents/${a.documentId}?includeTabsContent=true`);if(d._error)return out(d);{const z=end(d,a.tabId),q=[];if(z>1)q.push({deleteContentRange:{range:range(a,1,z)}});q.push({insertText:{location:loc(a,1),text:a.content}});r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:q});return out({documentId:a.documentId,replaced:!r._error,response:r,url:url(a.documentId)})}
 case"doc_insert_text":r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:[{insertText:{location:loc(a,a.index),text:a.content}}]});return out({documentId:a.documentId,inserted:!r._error,response:r,url:url(a.documentId)});
 case"doc_delete_range":r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:[{deleteContentRange:{range:range(a,a.startIndex,a.endIndex)}}]});return out({documentId:a.documentId,deleted:!r._error,response:r,url:url(a.documentId)});
 case"doc_find_replace":{const cr={text:a.find,matchCase:a.matchCase!==false};if(a.tabId)cr.tabIds=[a.tabId];r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:[{replaceAllText:{containsText:cr,replaceText:a.replace}}]});return out({documentId:a.documentId,replaced:!r._error,response:r,url:url(a.documentId)})}
 case"doc_update_text_style":r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:[{updateTextStyle:{range:range(a,a.startIndex,a.endIndex),textStyle:a.style,fields:a.fields}}]});return out({documentId:a.documentId,styled:!r._error,response:r,url:url(a.documentId)});
 case"doc_update_paragraph_style":r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:[{updateParagraphStyle:{range:range(a,a.startIndex,a.endIndex),paragraphStyle:a.style,fields:a.fields}}]});return out({documentId:a.documentId,styled:!r._error,response:r,url:url(a.documentId)});
 case"doc_insert_table":r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:[{insertTable:{rows:a.rows,columns:a.columns,location:loc(a,a.index)}}]});return out({documentId:a.documentId,inserted:!r._error,response:r,url:url(a.documentId)});
 case"doc_insert_image":r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:[{insertInlineImage:{location:loc(a,a.index),uri:a.imageUrl,objectSize:{width:{magnitude:a.widthPt||300,unit:"PT"},height:{magnitude:a.heightPt||200,unit:"PT"}}}}]});return out({documentId:a.documentId,inserted:!r._error,response:r,url:url(a.documentId)});
 case"doc_share":r=await perm(e,a.documentId,a.role||"reader");return out({documentId:a.documentId,shared:r.ok,role:a.role||"reader",url:url(a.documentId)});
 default:throw Error(`Unknown tool: ${n}`)}}
function rpc(id,result){return{jsonrpc:"2.0",id,result}}function err(id,c,m){return{jsonrpc:"2.0",id,error:{code:c,message:m}}}
async function route(e,q){const{method,params,id}=q;switch(method){case"initialize":return rpc(id,{protocolVersion:PROTOCOL_VERSION,capabilities:{tools:{listChanged:false}},serverInfo:SERVER_INFO});case"notifications/initialized":case"notifications/cancelled":return null;case"ping":return rpc(id,{});case"tools/list":return rpc(id,{tools:TOOLS});case"tools/call":try{return rpc(id,await handle(e,params?.name,params?.arguments))}catch(x){return rpc(id,{content:[{type:"text",text:`Error: ${x.message}`}],isError:true})}default:return err(id,-32601,`Method not found: ${method}`)}}
function auth(e,u){const r=`${u.origin}/callback`;return Response.redirect(`${AUTH_URL}?client_id=${encodeURIComponent(e.GOOGLE_CLIENT_ID)}&response_type=code&scope=${encodeURIComponent(SCOPES)}&redirect_uri=${encodeURIComponent(r)}&access_type=offline&prompt=consent`,302)}
async function callback(e,u){const c=u.searchParams.get("code"),x=u.searchParams.get("error");if(x)return new Response(`OAuth error: ${x}`,{status:400});if(!c)return new Response("Missing authorization code",{status:400});const r=`${u.origin}/callback`,z=await fetch(TOKEN_URL,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:`grant_type=authorization_code&code=${encodeURIComponent(c)}&redirect_uri=${encodeURIComponent(r)}&client_id=${encodeURIComponent(e.GOOGLE_CLIENT_ID)}&client_secret=${encodeURIComponent(e.GOOGLE_CLIENT_SECRET)}`});if(!z.ok)return new Response(`Token exchange failed: ${await z.text()}`,{status:500});await saveTokens(e,await z.json());return new Response("<h1>Connected to Google Docs</h1><p>You can close this window.</p>",{headers:{"Content-Type":"text/html"}})}
export default{async fetch(req,e){const u=new URL(req.url);if(u.pathname==="/health")return Response.json({status:"ok",google_connected:!!(await getTokens(e))?.refresh_token,version:SERVER_INFO.version});if(u.pathname==="/auth")return auth(e,u);if(u.pathname==="/callback")return callback(e,u);if(req.method==="OPTIONS")return new Response(null,{headers:{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization, Mcp-Session-Id"}});if(e.MCP_AUTH_TOKEN&&req.headers.get("Authorization")!==`Bearer ${e.MCP_AUTH_TOKEN}`)return new Response("Unauthorized",{status:401});if(!u.pathname.startsWith("/mcp"))return new Response("Not found",{status:404});if(req.method!=="POST")return new Response("Use POST for MCP requests",{status:405});let b;try{b=await req.json()}catch{return Response.json(err(null,-32700,"Parse error"),{status:400})}const h={"Content-Type":"application/json","Access-Control-Allow-Origin":"*"};if(Array.isArray(b)){const o=[];for(const q of b){const x=await route(e,q);if(x)o.push(x)}return o.length?Response.json(o,{headers:h}):new Response(null,{status:202,headers:h})}const o=await route(e,b);return o?Response.json(o,{headers:h}):new Response(null,{status:202,headers:h})}};
