// Google Docs MCP Server - structured editing
const SERVER_INFO={name:"google-docs-api",version:"1.3.0"};
const PROTOCOL_VERSION="2024-11-05";
const TOKEN_URL="https://oauth2.googleapis.com/token",AUTH_URL="https://accounts.google.com/o/oauth2/v2/auth",KV_KEY="google_oauth_tokens";
const SCOPES="https://www.googleapis.com/auth/documents https://www.googleapis.com/auth/drive.file";
async function getTokens(e){const r=await e.GOOGLE_TOKENS.get(KV_KEY);return r?JSON.parse(r):null}
async function saveTokens(e,t){const old=await getTokens(e);await e.GOOGLE_TOKENS.put(KV_KEY,JSON.stringify({access_token:t.access_token,refresh_token:t.refresh_token||old?.refresh_token,expires_at:Date.now()+(t.expires_in||3600)*1000-60000}))}
async function refresh(e){const t=await getTokens(e);if(!t?.refresh_token)throw Error("No refresh token. Visit /auth to authorize.");const r=await fetch(TOKEN_URL,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:`grant_type=refresh_token&refresh_token=${encodeURIComponent(t.refresh_token)}&client_id=${encodeURIComponent(e.GOOGLE_CLIENT_ID)}&client_secret=${encodeURIComponent(e.GOOGLE_CLIENT_SECRET)}`});if(!r.ok)throw Error(`Token refresh failed (${r.status}): ${await r.text()}`);const d=await r.json();await saveTokens(e,d);return d.access_token}
async function token(e){const t=await getTokens(e);if(!t)throw Error("Not authorized. Visit /auth to connect Google.");return Date.now()<t.expires_at?t.access_token:refresh(e)}
async function api(e,base,method,path,body){const h={Authorization:`Bearer ${await token(e)}`,Accept:"application/json"};if(body!==undefined)h["Content-Type"]="application/json";const r=await fetch(base+path,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body)}),txt=await r.text();if(!r.ok)return{_error:true,status:r.status,body:txt};try{return JSON.parse(txt)}catch{return txt}}
const docs=(e,m,p,b)=>api(e,"https://docs.googleapis.com/v1",m,p,b),drive=(e,m,p,b)=>api(e,"https://www.googleapis.com/drive/v3",m,p,b);
const result=d=>({content:[{type:"text",text:typeof d==="string"?d:JSON.stringify(d,null,2)}]});
function url(id){return `https://docs.google.com/document/d/${id}/edit`}
function textOf(doc){let s="";for(const x of doc.body?.content||[])for(const y of x.paragraph?.elements||[])if(y.textRun?.content)s+=y.textRun.content;return s}
function endIndex(doc){const b=doc.body?.content||[],x=b[b.length-1];return x?.endIndex?x.endIndex-1:1}
function tool(name,description,properties,required=[]){return{name,description,inputSchema:{type:"object",properties,required}}}
const S={type:"string"},N={type:"number"},BOOL={type:"boolean"};
const TOOLS=[
 tool("doc_create","Create a Google Doc with initial text, optionally in a Drive folder.",{title:S,content:S,folderId:S},["title","content"]),
 tool("doc_get","Read a Google Doc as plain text.",{documentId:S},["documentId"]),
 tool("doc_get_structure","Read the raw structured Google Docs document model, including paragraphs, tables, styles, and indexes.",{documentId:S},["documentId"]),
 tool("doc_append","Append text to the end of a Google Doc.",{documentId:S,content:S},["documentId","content"]),
 tool("doc_replace","Replace the entire body with text.",{documentId:S,content:S},["documentId","content"]),
 tool("doc_insert_text","Insert text at an exact character index.",{documentId:S,index:N,content:S},["documentId","index","content"]),
 tool("doc_delete_range","Delete content between exact character indexes.",{documentId:S,startIndex:N,endIndex:N},["documentId","startIndex","endIndex"]),
 tool("doc_find_replace","Find and replace text throughout a document.",{documentId:S,find:S,replace:S,matchCase:BOOL},["documentId","find","replace"]),
 tool("doc_update_text_style","Apply structured text formatting to a character range. Supports bold, italic, underline, strikethrough, fontSize, foregroundColor, backgroundColor, weightedFontFamily, and link.",{documentId:S,startIndex:N,endIndex:N,style:{type:"object"},fields:S},["documentId","startIndex","endIndex","style","fields"]),
 tool("doc_update_paragraph_style","Apply paragraph formatting to a range. Supports namedStyleType, alignment, lineSpacing, spaceAbove, spaceBelow, indentStart, indentEnd, and keepWithNext.",{documentId:S,startIndex:N,endIndex:N,style:{type:"object"},fields:S},["documentId","startIndex","endIndex","style","fields"]),
 tool("doc_insert_table","Insert a table at an exact character index.",{documentId:S,rows:N,columns:N,index:N},["documentId","rows","columns","index"]),
 tool("doc_insert_image","Insert a public image at an exact character index.",{documentId:S,imageUrl:S,index:N,widthPt:N,heightPt:N},["documentId","imageUrl","index"]),
 tool("doc_create_with_flowchart","Create a formatted Doc with text, a Mermaid flowchart, and trailing text.",{title:S,contentBefore:S,mermaidSource:S,contentAfter:S,folderId:S},["title","contentBefore","mermaidSource","contentAfter"]),
 tool("doc_share","Share a Doc with anyone by link at reader, commenter, or writer level.",{documentId:S,role:S},["documentId"])
];
function mermaid(s){return `https://mermaid.ink/img/${btoa(unescape(encodeURIComponent(s)))}`}
async function permission(e,id,role="reader"){return fetch(`https://www.googleapis.com/drive/v3/files/${id}/permissions`,{method:"POST",headers:{Authorization:`Bearer ${await token(e)}`,"Content-Type":"application/json"},body:JSON.stringify({role,type:"anyone"})})}
async function handle(e,name,a={}){let d,r;
 switch(name){
 case"doc_create":d=await docs(e,"POST","/documents",{title:a.title});if(d._error)return result(d);if(a.content)await docs(e,"POST",`/documents/${d.documentId}:batchUpdate`,{requests:[{insertText:{location:{index:1},text:a.content}}]});if(a.folderId)await drive(e,"PATCH",`/files/${d.documentId}?addParents=${encodeURIComponent(a.folderId)}&fields=id`,{});await permission(e,d.documentId);return result({documentId:d.documentId,title:a.title,url:url(d.documentId),shared:true});
 case"doc_get":d=await docs(e,"GET",`/documents/${a.documentId}`);return result(d._error?d:{documentId:d.documentId,title:d.title,content:textOf(d),url:url(d.documentId)});
 case"doc_get_structure":d=await docs(e,"GET",`/documents/${a.documentId}`);return result(d);
 case"doc_append":d=await docs(e,"GET",`/documents/${a.documentId}`);if(d._error)return result(d);r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:[{insertText:{location:{index:endIndex(d)},text:a.content}}]});return result({documentId:a.documentId,appended:!r._error,url:url(a.documentId),response:r});
 case"doc_replace":d=await docs(e,"GET",`/documents/${a.documentId}`);if(d._error)return result(d);{const end=endIndex(d),q=[];if(end>1)q.push({deleteContentRange:{range:{startIndex:1,endIndex:end}}});q.push({insertText:{location:{index:1},text:a.content}});r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:q});return result({documentId:a.documentId,replaced:!r._error,url:url(a.documentId),response:r})}
 case"doc_insert_text":r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:[{insertText:{location:{index:a.index},text:a.content}}]});return result({documentId:a.documentId,inserted:!r._error,response:r,url:url(a.documentId)});
 case"doc_delete_range":r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:[{deleteContentRange:{range:{startIndex:a.startIndex,endIndex:a.endIndex}}}]});return result({documentId:a.documentId,deleted:!r._error,response:r,url:url(a.documentId)});
 case"doc_find_replace":r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:[{replaceAllText:{containsText:{text:a.find,matchCase:a.matchCase!==false},replaceText:a.replace}}]});return result({documentId:a.documentId,replaced:!r._error,response:r,url:url(a.documentId)});
 case"doc_update_text_style":r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:[{updateTextStyle:{range:{startIndex:a.startIndex,endIndex:a.endIndex},textStyle:a.style,fields:a.fields}}]});return result({documentId:a.documentId,styled:!r._error,response:r,url:url(a.documentId)});
 case"doc_update_paragraph_style":r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:[{updateParagraphStyle:{range:{startIndex:a.startIndex,endIndex:a.endIndex},paragraphStyle:a.style,fields:a.fields}}]});return result({documentId:a.documentId,styled:!r._error,response:r,url:url(a.documentId)});
 case"doc_insert_table":r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:[{insertTable:{rows:a.rows,columns:a.columns,location:{index:a.index}}}]});return result({documentId:a.documentId,inserted:!r._error,response:r,url:url(a.documentId)});
 case"doc_insert_image":r=await docs(e,"POST",`/documents/${a.documentId}:batchUpdate`,{requests:[{insertInlineImage:{location:{index:a.index},uri:a.imageUrl,objectSize:{width:{magnitude:a.widthPt||300,unit:"PT"},height:{magnitude:a.heightPt||200,unit:"PT"}}}}]});return result({documentId:a.documentId,inserted:!r._error,response:r,url:url(a.documentId)});
 case"doc_create_with_flowchart":{d=await docs(e,"POST","/documents",{title:a.title});if(d._error)return result(d);const id=d.documentId;await docs(e,"POST",`/documents/${id}:batchUpdate`,{requests:[{insertText:{location:{index:1},text:a.contentBefore+"\n"}}]});let cur=await docs(e,"GET",`/documents/${id}`);await docs(e,"POST",`/documents/${id}:batchUpdate`,{requests:[{insertInlineImage:{location:{index:endIndex(cur)},uri:mermaid(a.mermaidSource),objectSize:{width:{magnitude:300,unit:"PT"},height:{magnitude:350,unit:"PT"}}}}]});cur=await docs(e,"GET",`/documents/${id}`);await docs(e,"POST",`/documents/${id}:batchUpdate`,{requests:[{insertText:{location:{index:endIndex(cur)},text:"\n"+a.contentAfter}}]});if(a.folderId)await drive(e,"PATCH",`/files/${id}?addParents=${encodeURIComponent(a.folderId)}&fields=id`,{});await permission(e,id);return result({documentId:id,title:a.title,url:url(id),shared:true})}
 case"doc_share":r=await permission(e,a.documentId,a.role||"reader");return result({documentId:a.documentId,shared:r.ok,role:a.role||"reader",url:url(a.documentId)});
 default:throw Error(`Unknown tool: ${name}`)
 }}
function rpc(id,result){return{jsonrpc:"2.0",id,result}}function rpcErr(id,c,m){return{jsonrpc:"2.0",id,error:{code:c,message:m}}}
async function route(e,q){const{method,params,id}=q;switch(method){case"initialize":return rpc(id,{protocolVersion:PROTOCOL_VERSION,capabilities:{tools:{listChanged:false}},serverInfo:SERVER_INFO});case"notifications/initialized":case"notifications/cancelled":return null;case"ping":return rpc(id,{});case"tools/list":return rpc(id,{tools:TOOLS});case"tools/call":try{return rpc(id,await handle(e,params?.name,params?.arguments))}catch(x){return rpc(id,{content:[{type:"text",text:`Error: ${x.message}`}],isError:true})}default:return rpcErr(id,-32601,`Method not found: ${method})`)} }
function auth(e,u){const red=`${u.origin}/callback`;return Response.redirect(`${AUTH_URL}?client_id=${encodeURIComponent(e.GOOGLE_CLIENT_ID)}&response_type=code&scope=${encodeURIComponent(SCOPES)}&redirect_uri=${encodeURIComponent(red)}&access_type=offline&prompt=consent`,302)}
async function callback(e,u){const code=u.searchParams.get("code"),err=u.searchParams.get("error");if(err)return new Response(`OAuth error: ${err}`,{status:400});if(!code)return new Response("Missing authorization code",{status:400});const red=`${u.origin}/callback`,r=await fetch(TOKEN_URL,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:`grant_type=authorization_code&code=${encodeURIComponent(code)}&redirect_uri=${encodeURIComponent(red)}&client_id=${encodeURIComponent(e.GOOGLE_CLIENT_ID)}&client_secret=${encodeURIComponent(e.GOOGLE_CLIENT_SECRET)}`});if(!r.ok)return new Response(`Token exchange failed: ${await r.text()}`,{status:500});await saveTokens(e,await r.json());return new Response("<h1>Connected to Google Docs</h1><p>You can close this window.</p>",{headers:{"Content-Type":"text/html"}})}
export default{async fetch(req,e){const u=new URL(req.url);if(u.pathname==="/health")return Response.json({status:"ok",google_connected:!!(await getTokens(e))?.refresh_token});if(u.pathname==="/auth")return auth(e,u);if(u.pathname==="/callback")return callback(e,u);if(req.method==="OPTIONS")return new Response(null,{headers:{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization, Mcp-Session-Id"}});if(e.MCP_AUTH_TOKEN&&req.headers.get("Authorization")!==`Bearer ${e.MCP_AUTH_TOKEN}`)return new Response("Unauthorized",{status:401});if(!u.pathname.startsWith("/mcp"))return new Response("Not found",{status:404});if(req.method!=="POST")return new Response("Use POST for MCP requests",{status:405});let body;try{body=await req.json()}catch{return Response.json(rpcErr(null,-32700,"Parse error"),{status:400})}const h={"Content-Type":"application/json","Access-Control-Allow-Origin":"*"};if(Array.isArray(body)){const out=[];for(const q of body){const x=await route(e,q);if(x)out.push(x)}return out.length?Response.json(out,{headers:h}):new Response(null,{status:202,headers:h})}const out=await route(e,body);return out?Response.json(out,{headers:h}):new Response(null,{status:202,headers:h})}};
